### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by afterlifenirvana** [teeks99/py_boost_shmem#1]
Hi. 
I was referring to your repo for the shared memory and i was not able to run it.

I'm getting errors.

Traceback (most recent call last):
  File "shmem.py", line 19, in <module>
    "TransferDataSHMEM")
TypeError: an integer is required (got type str)

please if you can help me out. I need this urgent.

**Comment by afterlifenirvana** [comment]
I'm running this on ubuntu..

**Comment by teeks99** [comment]
This is because the example code is for shared memory operations on **windows**. If you look at the [python documentation for mmap](https://docs.python.org/3.6/library/mmap.html) you can see that the setup function is different for windows/linux, and that is what you are running into.

**Comment by afterlifenirvana** [comment]
yeah. I saw that already. I opened this issue to ask for help if i can work around that somehow ?  cause  I'm stuck as there is no tag_name for unix version.

**Comment by afterlifenirvana** [comment]
I need to use this in a project where i need the data to be transferred from c++ to python. I tried using redis and kafka as message broker but i have come to understanding that they will be too slow for my requirement. I need to somehow use the fastest method. if you can help would be much appreciated. @teeks99
